"""
MESA-style stellar profile reader.

Accepts simple column-table files with a header line naming the columns,
followed by numeric rows.  Format:

    # arbitrary comment
    # arbitrary comment
    r  rho  N2  cs2
    0.2  0.123  0.000  1.50
    ...

Columns required: r, rho, N2, cs2 (radius, density, Brunt² squared, sound
speed squared).  Header line is the first non-comment, non-numeric line.
The real MESA `profile*.data` has a much richer header and column set; this
parser reads the minimal subset we need for the Cowling g-mode equation.

A sample fixture can be generated by `build_polytrope_fixture()` (n=3
polytrope density profile + imposed Gaussian-bump N²(r) for the cavity;
the two are not thermodynamically self-consistent but the Cowling equation
only consumes ρ (for evanescence diagnostics) and N²).
"""
from __future__ import annotations

import io
from pathlib import Path
from typing import Dict

import numpy as np
import scipy.integrate


REQUIRED = ("r", "rho", "N2", "cs2")


def read_profile(path: str | Path) -> Dict[str, np.ndarray]:
    """Read a column-table profile.

    Returns a dict with keys including at least REQUIRED.  Values are 1D
    numpy arrays, shape (N,).  Rows must be sorted by ascending r.
    """
    path = Path(path)
    with path.open() as f:
        lines = [ln for ln in f if ln.strip() and not ln.lstrip().startswith("#")]
    if not lines:
        raise ValueError(f"{path}: empty profile")

    header = lines[0].split()
    data_rows = lines[1:]
    n_cols = len(header)

    # Parse numeric rows
    mat = np.empty((len(data_rows), n_cols))
    for i, ln in enumerate(data_rows):
        toks = ln.split()
        if len(toks) != n_cols:
            raise ValueError(
                f"{path}:{i+2}: got {len(toks)} columns, header promised {n_cols}")
        mat[i] = [float(t) for t in toks]

    profile = {col: mat[:, j] for j, col in enumerate(header)}

    missing = set(REQUIRED) - set(profile)
    if missing:
        raise ValueError(f"{path}: missing required columns {missing}")

    # Enforce r ascending
    if np.any(np.diff(profile["r"]) <= 0):
        order = np.argsort(profile["r"])
        profile = {k: v[order] for k, v in profile.items()}

    return profile


def build_polytrope_fixture(path: str | Path,
                            n_poly: float = 3.0,
                            n_pts: int = 600,
                            gamma: float = 5.0 / 3.0,
                            K_poly: float = 1.0,
                            cavity_r_lo: float = 0.2,
                            cavity_r_hi: float = 0.95,
                            N2_amp: float = 1.0) -> None:
    """Write a Lane-Emden polytropic profile with an imposed N²(r) bump.

    Physics:
      * rho(r) from Lane-Emden(n=3): P = K rho^{1 + 1/n}.
      * cs² = gamma * P / rho computed consistently from rho and K_poly.
      * N²(r): Gaussian-bump taper on [cavity_r_lo, cavity_r_hi] matching the
        structure used in gmode_exp_b_stratified.py / _c_chebyshev.py, so a
        downstream Cowling solve reproduces their numbers.

    The Gaussian-bump N²(r) is NOT thermodynamically derived from the
    polytrope (which is isentropic and has N² = 0).  This is deliberate:
    MESA's own N² output is similarly independent of the structure profile
    from the Cowling equation's perspective; the solver just reads both.
    Comment this in the file header so a downstream reader knows.
    """
    # Lane-Emden solve (reused algorithmically from gmode_infra.solve_lane_emden;
    # we copy it locally to avoid a circular import at fixture-build time).
    def rhs(xi, y):
        theta, dtheta = y
        if xi < 1e-10:
            return [dtheta, -theta ** n_poly / 3.0]
        theta_pow = np.sign(theta) * np.abs(theta) ** n_poly if theta >= 0 else 0.0
        return [dtheta, -2.0 / xi * dtheta - theta_pow]

    def event_zero(xi, y):
        return y[0]
    event_zero.terminal = True
    event_zero.direction = -1

    sol = scipy.integrate.solve_ivp(
        rhs, [1e-6, 12.0], [1.0 - 1e-12, 0.0],
        events=event_zero, max_step=0.01, rtol=1e-10, atol=1e-12,
        dense_output=True,
    )
    xi_1 = sol.t_events[0][0] if sol.t_events[0].size else sol.t[-1]
    xi = np.linspace(1e-5, xi_1 * 0.999, n_pts)
    theta = sol.sol(xi)[0]

    r = xi / xi_1                              # normalised radius r ∈ [0,1)
    rho = np.abs(theta) ** n_poly              # ρ = ρ_c θ^n, ρ_c := 1
    P = K_poly * rho ** (1.0 + 1.0 / n_poly)   # polytropic EOS
    cs2 = gamma * np.where(rho > 0, P / np.maximum(rho, 1e-30), 0.0)

    # Imposed N²(r): Gaussian × sin² taper on [cavity_r_lo, cavity_r_hi]
    rc = 0.5 * (cavity_r_lo + cavity_r_hi)
    sigma = 0.25 * (cavity_r_hi - cavity_r_lo)
    bump = np.exp(-((r - rc) / sigma) ** 2)
    taper = np.where(
        (r >= cavity_r_lo) & (r <= cavity_r_hi),
        np.sin(np.pi * (r - cavity_r_lo) / (cavity_r_hi - cavity_r_lo)) ** 2,
        0.0,
    )
    N2 = N2_amp * bump * taper

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        f.write(f"# polytropic fixture, n_poly={n_poly}, gamma={gamma}\n")
        f.write(f"# cavity: [{cavity_r_lo}, {cavity_r_hi}], N2_amp={N2_amp}\n")
        f.write(f"# N2 is imposed (Gaussian bump), not derived from entropy\n")
        f.write(f"# columns: r rho N2 cs2\n")
        f.write("r rho N2 cs2\n")
        for i in range(len(r)):
            f.write(f"{r[i]:.10e} {rho[i]:.10e} {N2[i]:.10e} {cs2[i]:.10e}\n")
