#!/usr/bin/env python3
"""T5 / Phase A.2 (task #49) — Archive Andrassy 2022 resolution scan into
`docs/scheme_char/`.

Walks the scheme_scan_{128,256,512}/ trees generated by
scripts/andrassy2022/run_ale2_scan.sh and the athena_vl2_scan_v2 tree
generated by its sibling.  For each (code, res, scheme) triple, extracts
steady-state v_rms, y_ub, and entrainment rate Ṁ_e averaged over the
quasi-stationary window, and emits:

    docs/scheme_char/2026-05-07_andrassy_vrms_vs_res.csv
    docs/scheme_char/2026-05-07_andrassy_vrms_vs_res.png
    docs/scheme_char/2026-05-07_andrassy_vrms_vs_res.md   (hand-written)

This file contains the CSV + figure; the interpretive markdown is kept
next to it and should be hand-edited.
"""
from __future__ import annotations

import csv
import glob
from pathlib import Path
from typing import Optional

import numpy as np
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[2]
OUT_DIR = REPO / "docs" / "scheme_char"
DATE = "2026-05-07"

LX = 2.0  # Andrassy 2022 slab half-width in code units.

# (code, res, scheme, label, color, marker, run_glob, t_lo, t_hi)
# Same glob patterns as scripts/andrassy2022/paper_scan_figure.py.
RUNS = [
    # Eulerian Godunov (vl2)
    ("vl2", 128, "VL",  "Athena PLM-VL", "#1f77b4", "o",
     "runs/athena_vl2_scan_v2/128_vanleer/andrassy2022_128x128_*", 1000, 2000),
    ("vl2", 256, "VL",  "Athena PLM-VL", "#1f77b4", "o",
     "runs/athena_vl2_scan_v2/256_vanleer/andrassy2022_256x256_*", 1000, 2000),
    ("vl2", 512, "VL",  "Athena PLM-VL", "#1f77b4", "o",
     "runs/athena_vl2_scan_v2/512_vanleer/andrassy2022_512x512_*", 1000, 2000),
    ("vl2", 128, "MM",  "Athena PLM-MM", "#1f77b4", "s",
     "runs/athena_vl2_scan_v2/128_minmod/andrassy2022_128x128_*", 1000, 2000),
    ("vl2", 256, "MM",  "Athena PLM-MM", "#1f77b4", "s",
     "runs/athena_vl2_scan_v2/256_minmod/andrassy2022_256x256_*", 1000, 2000),
    ("vl2", 512, "MM",  "Athena PLM-MM", "#1f77b4", "s",
     "runs/athena_vl2_scan_v2/512_minmod/andrassy2022_512x512_*", 1000, 2000),
    # Lagrangian ALE
    ("ale2", 128, "VL",  "ALE MUSCL-VL",  "#d62728", "o",
     "runs/scheme_scan_128/muscl_vanleer/andrassy2022_128x128_*", 100, 400),
    ("ale2", 128, "MM",  "ALE MUSCL-MM",  "#d62728", "s",
     "runs/scheme_scan_128/muscl_minmod/andrassy2022_128x128_*", 100, 400),
    ("ale2", 128, "PPM", "ALE PPM-CS",    "#d62728", "D",
     "runs/scheme_scan_128/ppm_cs_char/andrassy2022_128x128_*",  100, 400),
    ("ale2", 256, "MC",  "ALE MUSCL-MC",  "#d62728", "^",
     "runs/scheme_scan_256/muscl_mc/andrassy2022_256x256_*",     1000, 2000),
    ("ale2", 256, "VL",  "ALE MUSCL-VL",  "#d62728", "o",
     "runs/scheme_scan_256/muscl_vanleer/andrassy2022_256x256_*",1000, 2000),
    ("ale2", 256, "MM",  "ALE MUSCL-MM",  "#d62728", "s",
     "runs/scheme_scan_256/muscl_minmod/andrassy2022_256x256_*", 1000, 2000),
    ("ale2", 256, "PPM", "ALE PPM-CS",    "#d62728", "D",
     "runs/scheme_scan_256/ppm_cs_prim/andrassy2022_256x256_*",  1000, 2000),
    ("ale2", 512, "VL",  "ALE MUSCL-VL",  "#d62728", "o",
     "runs/scheme_scan_512/muscl_vanleer/andrassy2022_512x512_*",1000, 2000),
    ("ale2", 512, "MM",  "ALE MUSCL-MM",  "#d62728", "s",
     "runs/scheme_scan_512/muscl_minmod/andrassy2022_512x512_*", 1000, 2000),
    ("ale2", 512, "PPM", "ALE PPM-CS",    "#d62728", "D",
     "runs/scheme_scan_512/ppm_cs_char/andrassy2022_512x512_*",  1000, 2000),
]


def load(pat: str) -> Optional[np.ndarray]:
    fs = sorted(glob.glob(str(REPO / pat)))
    if not fs:
        return None
    try:
        return np.loadtxt(fs[-1], delimiter=",", skiprows=1)
    except Exception as e:
        print(f"  [warn] {fs[-1]}: {e}")
        return None


def avg_col(d: Optional[np.ndarray], c: int, lo: float, hi: float) -> Optional[float]:
    if d is None:
        return None
    t = d[:, 0]
    v = d[:, c]
    m = (t >= lo) & (t <= hi) & ~np.isnan(v)
    return float(np.nanmean(v[m])) if m.sum() >= 3 else None


def fit_md(d: Optional[np.ndarray], lo: float, hi: float) -> Optional[float]:
    """Linear fit of M_e(t) over [lo, hi]."""
    if d is None:
        return None
    t = d[:, 0]
    Me = d[:, 2]
    ok = ~np.isnan(Me)
    t = t[ok]; Me = Me[ok]
    m = (t >= lo) & (t <= hi)
    if m.sum() < 3:
        return None
    return float(np.polyfit(t[m], Me[m], 1)[0])


def gather():
    rows = []
    for (code, res, sch, lab, col, mkr, glob_pat, lo, hi) in RUNS:
        ts = load(f"{glob_pat}/timeseries.csv")
        ent = load(f"{glob_pat}/entrainment.csv")
        vr = avg_col(ts, 3, lo, hi)      # v_rms_conv
        yu = avg_col(ts, 2, lo, hi)      # y_ub
        md = fit_md(ent, lo, hi)
        rows.append(dict(code=code, res=res, sch=sch, label=lab,
                         color=col, marker=mkr, window=(lo, hi),
                         v_rms=vr, y_ub=yu, Mdot=md))
    return rows


def write_csv(rows) -> Path:
    path = OUT_DIR / f"{DATE}_andrassy_vrms_vs_res.csv"
    with path.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["code", "res", "scheme", "label",
                    "t_lo", "t_hi", "v_rms_conv", "y_ub", "Mdot_e"])
        for r in rows:
            w.writerow([r["code"], r["res"], r["sch"], r["label"],
                        r["window"][0], r["window"][1],
                        "" if r["v_rms"] is None else f"{r['v_rms']:.6e}",
                        "" if r["y_ub"]  is None else f"{r['y_ub']:.6e}",
                        "" if r["Mdot"]  is None else f"{r['Mdot']:.6e}"])
    print(f"Wrote {path}")
    return path


def plot_scan(rows) -> Path:
    fig, (ax_v, ax_md) = plt.subplots(1, 2, figsize=(11, 4.5))

    def plot_obs(ax, key, ylabel):
        seen = set()
        for r in rows:
            if r[key] is None:
                continue
            y = r[key]
            if key == "Mdot":
                y = y / LX
            tag = (r["code"], r["sch"])
            kw = dict(marker=r["marker"], color=r["color"], ls="",
                      markersize=8)
            if tag not in seen:
                kw["label"] = r["label"]
                seen.add(tag)
            ax.plot(r["res"], y, **kw)
        ax.set_xlabel("resolution N")
        ax.set_ylabel(ylabel)
        ax.set_xscale("log", base=2)
        ax.set_xticks([128, 256, 512])
        ax.set_xticklabels(["128", "256", "512"])
        ax.grid(alpha=0.3)
        ax.legend(fontsize=7, loc="best")

    plot_obs(ax_v,  "v_rms", r"$v_{\rm rms,conv}$  (code units)")
    plot_obs(ax_md, "Mdot",  r"$\dot M_e / L_x$  (code units)")
    ax_v.set_title("Andrassy 2022 — v_rms vs resolution")
    ax_md.set_title("Andrassy 2022 — entrainment vs resolution")
    fig.tight_layout()
    path = OUT_DIR / f"{DATE}_andrassy_vrms_vs_res.png"
    fig.savefig(path, dpi=140)
    print(f"Wrote {path}")
    return path


if __name__ == "__main__":
    rows = gather()
    n_ok = sum(1 for r in rows if r["v_rms"] is not None)
    print(f"Gathered {len(rows)} run specs, {n_ok} with v_rms data")
    write_csv(rows)
    plot_scan(rows)
