#!/usr/bin/env python3
"""Plot DNS Experiment A (3-wave triad) GPU results.
Output: paper/figures/fig7_1_triad.png

Shows modal energy E_k1..4 and total energy drift over 100 g-mode periods
at three amplitudes (1e-6, 1e-5, 1e-4) on Lane-Emden n=3/2.

Generated by the GPU Strang-split extension of Path D; reads runs from
runs/dns_expA/triad_amp{1e-6,1e-5,1e-4}.csv produced by
--solver anelastic_sl --test dns_triad.
"""
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

amps = ["1e-6", "1e-5", "1e-4"]
colors = {"1e-6": "#1f77b4", "1e-5": "#ff7f0e", "1e-4": "#2ca02c"}

fig, axes = plt.subplots(2, 2, figsize=(12, 9))
(ax_ek, ax_dev, ax_et, ax_sp) = axes.flat

for amp in amps:
    path = f"runs/dns_expA/triad_amp{amp}.csv"
    data = np.loadtxt(path, comments="#")
    # columns: t, v_center, eigmode_dev, E_total, E_k1, E_k2, E_k3, E_k4, max_abs_v
    t = data[:, 0]
    dev = data[:, 2]
    Et = data[:, 3]
    Ek = data[:, 4:8]   # k=1..4

    with open(path) as f:
        hdr = f.readline()
    T_period = float([p for p in hdr.split() if p.startswith("period=")][0].split("=")[1])
    n_periods = t / T_period

    lbl = f"amp={amp}"
    E_k1_0 = Ek[0, 0]
    ax_ek.plot(n_periods, Ek[:, 0] / E_k1_0, label=f"k=1 ({lbl})",
               color=colors[amp], lw=1.5)
    ax_ek.plot(n_periods, Ek[:, 1] / E_k1_0, label=f"k=2 ({lbl})",
               color=colors[amp], lw=1.0, ls="--")

    ax_dev.plot(n_periods, dev, label=lbl, color=colors[amp])

    if Et[0] > 0:
        ax_et.plot(n_periods, np.abs(Et - Et[0]) / Et[0] + 1e-16,
                   label=lbl, color=colors[amp])

    ax_sp.semilogy(np.arange(1, 5), Ek[-1, :] / E_k1_0 + 1e-40,
                   "o-", label=lbl, color=colors[amp])

ax_ek.set_xlabel("periods of g-mode n_g=1")
ax_ek.set_ylabel("E_k / E_k1(0)")
ax_ek.set_yscale("log")
ax_ek.set_title("Modal energy: primary (solid) + second harmonic (dashed)")
ax_ek.legend(loc="upper right", fontsize=8, ncol=2)
ax_ek.grid(True, alpha=0.3)

ax_dev.set_xlabel("periods")
ax_dev.set_ylabel("eigmode deviation")
ax_dev.set_title("Primary-mode deviation vs time")
ax_dev.set_yscale("log")
ax_dev.legend()
ax_dev.grid(True, alpha=0.3)

ax_et.set_xlabel("periods")
ax_et.set_ylabel("|ΔE / E(0)|")
ax_et.set_yscale("log")
ax_et.set_title("Total-energy drift (anelastic functional)")
ax_et.legend()
ax_et.grid(True, alpha=0.3)

ax_sp.set_xlabel("horizontal mode k")
ax_sp.set_ylabel("E_k / E_k1(0) at t=100 periods")
ax_sp.set_yscale("log")
ax_sp.set_title("Modal spectrum at end of run")
ax_sp.set_xticks([1, 2, 3, 4])
ax_sp.legend()
ax_sp.grid(True, alpha=0.3)

plt.suptitle("DNS Experiment A: 3-wave triad, Lane-Emden n=3/2, 64×64, GPU Strang-split RK4",
             fontsize=11)
plt.tight_layout()
out = "paper/figures/fig7_1_triad.png"
plt.savefig(out, dpi=140, bbox_inches="tight")
print(f"saved → {out}")

print("\nSummary:")
for amp in amps:
    data = np.loadtxt(f"runs/dns_expA/triad_amp{amp}.csv", comments="#")
    t, dev, Et = data[:, 0], data[:, 2], data[:, 3]
    Ek = data[:, 4:8]
    E_k1_0 = Ek[0, 0]
    dev_100 = dev[-1]
    dev_rate = dev[-1] / 100.0
    E_k1_drift = (Ek[-1, 0] - Ek[0, 0]) / Ek[0, 0]
    E_k2_end = Ek[-1, 1] / E_k1_0
    print(f"  amp={amp}:  dev(100T)={dev_100:.3e}, dev/period={dev_rate:.3e}, "
          f"E_k1 drift={E_k1_drift:+.3e}, E_k2/E_k1_0 = {E_k2_end:.3e}")
