r"""
docs/derivations/mhd/scripts/_common.py — shared sympy utilities.

Every derivation script imports from here. Philosophy:
- Define symbols once, centrally, so every section uses the same
  conventions (e.g., everyone means the same thing by `rho`, `B_x`).
- Provide LaTeX dump helpers so each script can write a uniform
  `output/<script>.latex.tex` file that the markdown sections \input.
- Provide `assert_zero(expr, name)` that (a) runs sp.simplify,
  (b) raises with a human-readable message, (c) if not zero, prints
  the sympy form so debugging is immediate.
"""
from __future__ import annotations

import sys
from pathlib import Path

import sympy as sp

# ════════════════════════════════════════════════════════════
# Symbol inventory (shared across sections).  MHD conventions:
#   - SI-ish with 4π absorbed into B definition (Gaussian-style),
#     consistent with Stone+08, Athena++, most astro MHD references.
#   - B unit: √(4πρ₀)·c_A so that A_A = B/√ρ naturally, skipping the
#     √(4π) factor in the momentum flux ½|B|²/4π.
# ════════════════════════════════════════════════════════════

# scalar state variables (positive where applicable)
rho = sp.Symbol("rho", positive=True)
p = sp.Symbol("p", positive=True)           # gas pressure
T = sp.Symbol("T", positive=True)
e = sp.Symbol("e", positive=True)           # specific internal energy
E = sp.Symbol("E", positive=True)           # total energy per volume
gamma = sp.Symbol("gamma", positive=True)    # ratio of specific heats

# velocity and magnetic-field cartesian components
v_x, v_y, v_z = sp.symbols("v_x v_y v_z", real=True)
B_x, B_y, B_z = sp.symbols("B_x B_y B_z", real=True)

# conservative variables (momentum m = rho·v)
m_x, m_y, m_z = sp.symbols("m_x m_y m_z", real=True)

# coordinates & time
x, y, z, r, theta, phi, t = sp.symbols("x y z r theta phi t", real=True)

# wavenumbers
k, k_x, k_y, k_z = sp.symbols("k k_x k_y k_z", real=True)

# constants
mu_0 = sp.Symbol("mu_0", positive=True)     # kept for optional SI switch
k_B  = sp.Symbol("k_B", positive=True)
G_grav = sp.Symbol("G", positive=True)       # Newton's G (not to confuse)
M_star = sp.Symbol("M_star", positive=True)
R_star = sp.Symbol("R_star", positive=True)

# ════════════════════════════════════════════════════════════
# Vector / tensor helpers
# ════════════════════════════════════════════════════════════
def vec(xc, yc, zc):
    """Return a 3-vector as a sp.Matrix column."""
    return sp.Matrix([xc, yc, zc])

def cross(a, b):
    """Cross product of two 3-vectors (sp.Matrix columns)."""
    ax, ay, az = a
    bx, by, bz = b
    return sp.Matrix([
        ay*bz - az*by,
        az*bx - ax*bz,
        ax*by - ay*bx,
    ])

def dot(a, b):
    return (a.T @ b)[0, 0]

def div_cart(V, coords=(x, y, z)):
    """Divergence of vector field V = [Vx, Vy, Vz] in Cartesian."""
    return sum(sp.diff(V[i], coords[i]) for i in range(3))

def grad_cart(f, coords=(x, y, z)):
    return sp.Matrix([sp.diff(f, c) for c in coords])

def curl_cart(V, coords=(x, y, z)):
    Vx, Vy, Vz = V
    X, Y, Z = coords
    return sp.Matrix([
        sp.diff(Vz, Y) - sp.diff(Vy, Z),
        sp.diff(Vx, Z) - sp.diff(Vz, X),
        sp.diff(Vy, X) - sp.diff(Vx, Y),
    ])


# ════════════════════════════════════════════════════════════
# LaTeX dump + assertion utilities
# ════════════════════════════════════════════════════════════
OUT_DIR = Path(__file__).resolve().parent.parent / "output"
OUT_DIR.mkdir(parents=True, exist_ok=True)


class LatexDump:
    """
    Accumulate LaTeX-formatted equations and write them out to
    output/<script_stem>.latex.tex.  Each call to .add() appends an
    aligned equation block with an optional label.

    Typical use:
        ld = LatexDump(__file__)
        ld.add("Mass conservation",
               "\\partial_t \\rho + \\nabla \\cdot (\\rho \\mathbf{v}) = 0",
               label="eq:mass")
        ld.write()
    """
    def __init__(self, script_path: str | Path):
        stem = Path(script_path).stem
        self.out_path = OUT_DIR / f"{stem}.latex.tex"
        self.entries: list[tuple[str, str, str | None]] = []
        self.script_stem = stem

    def add(self, name: str, latex: str, label: str | None = None):
        self.entries.append((name, latex, label))

    def add_expr(self, name: str, expr, label: str | None = None):
        """Convenience: hand over a sympy expr instead of raw LaTeX."""
        self.entries.append((name, sp.latex(expr), label))

    def add_equation(self, name: str, lhs, rhs, label: str | None = None):
        """Emit `<LaTeX(lhs)> = <LaTeX(rhs)>`."""
        self.entries.append(
            (name, f"{sp.latex(lhs)} = {sp.latex(rhs)}", label)
        )

    def write(self):
        lines = [
            f"% Auto-generated by scripts/{self.script_stem}.py",
            f"% Do not edit manually.",
            "",
        ]
        for name, latex, label in self.entries:
            lines.append(f"% {name}")
            if label:
                lines.append(
                    "\\begin{equation}\\label{" + label + "}\n"
                    + latex
                    + "\n\\end{equation}"
                )
            else:
                lines.append("\\begin{equation*}\n" + latex + "\n\\end{equation*}")
            lines.append("")
        self.out_path.write_text("\n".join(lines))
        print(f"  → wrote {self.out_path.relative_to(OUT_DIR.parent)}")


def assert_zero(expr, name: str, trig: bool = False, verbose: bool = True):
    """
    Assert sp.simplify(expr) == 0.  If `trig=True` apply trig-simp first.
    On failure prints expr and raises AssertionError with name.
    """
    simplified = sp.simplify(expr)
    if trig:
        simplified = sp.trigsimp(simplified)
    if simplified != 0:
        msg = (
            f"[FAIL] {name}: expected 0, got {simplified}\n"
            f"       raw expr: {expr}"
        )
        print(msg, file=sys.stderr)
        raise AssertionError(msg)
    if verbose:
        print(f"  [OK] {name} — sympy verified to 0.")


def banner(title: str):
    """Pretty-print a section banner to stdout."""
    print()
    print("═" * 60)
    print(f"  {title}")
    print("═" * 60)
